branch-defaults:
  default:
    environment: jessica-aws-dev
    group_suffix: null
global:
  application_name: jessica_aws
  default_ec2_keyname: jessica-keypair
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: null
